### ISSUE TITLE
CONEXIÓN_DE_DATOS

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-tec-design#1]
[R1_Ejercicio1_conexion_a_la_BD.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-tec-design/files/15458857/R1_Ejercicio1_conexion_a_la_BD.pdf)

**Comment by josealfredo79** [comment]
Calificacion 20
